### ISSUE TITLE
new Dashboard

### ISSUE THREAD

**Issue by M1stv1eh** [dennistreysa/CoordsChanger#1]
Der Button, mit dem das Bearbeitungsfeld für eine große Anzahl zu ändernden Koordinaten geöffnet wird, existiert nur in der alten Anzeige bei Geocaching.com 
Auf dem neuen Dashboard ist der Button nicht mehr zu sehen und um das Script ausführen zu können, muss auf die alte Ansicht zurück gestellt werden.
Thx
René

**Comment by patricks** [comment]
Es würde für das Problem schon einen PR #2 geben.

**Comment by dennistreysa** [comment]
Pull Request #2  wurde eingearbeitet. In der aktuellen Dev-Version scheint alles wieder zu gehen (Chrome & Firefox): https://github.com/dennistreysa/CoordsChanger/raw/dev/coordschanger.latest.user.js

Ich habe den Button mal ein wenig höher einsortiert, direkt unter "Your Lists".

![Position](https://user-images.githubusercontent.com/6089938/73702732-f2a03300-46ed-11ea-81de-581f9a668540.PNG)

Viel Spaß ;)
